# Generated by Django 5.2.4 on 2025-08-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_verification_enabled', models.BooleanField(default=True, help_text='Globally enable or disable all camera functions (enrollment, check-in, etc.).')),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
