# Generated by Django 5.2.4 on 2025-08-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='location_verification_enabled',
            field=models.BooleanField(default=True, help_text='Globally enable or disable the GPS/location check during check-in.'),
        ),
    ]
