# Generated by Django 5.2.4 on 2025-07-23 03:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='logs.activitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServerRoomAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_timestamp', models.DateTimeField(blank=True, null=True)),
                ('exit_timestamp', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(help_text='Describe the purpose of your visit.')),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Checked-In', 'Checked-In'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('entry_photo', models.ImageField(blank=True, null=True, upload_to='access_photos/check_in/')),
                ('activity_report', models.TextField(blank=True, help_text='Summary of activities performed.')),
                ('outcome', models.CharField(blank=True, choices=[('Success', 'Success'), ('Partial', 'Partial Success'), ('Failed', 'Failed')], max_length=20)),
                ('additional_persons', models.ManyToManyField(blank=True, related_name='accompanying_logs', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_logs', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.activitycategory')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.serverlocation')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.activitysubcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
