# Generated by Django 5.2.4 on 2025-07-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverroomaccesslog',
            name='non_registered_persons',
            field=models.TextField(blank=True, help_text='Enter the full names of any non-registered guests, one per line.'),
        ),
    ]
