# Generated by Django 5.2.4 on 2025-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_serverroomaccesslog_non_registered_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverroomaccesslog',
            name='additional_persons',
        ),
        migrations.RemoveField(
            model_name='serverroomaccesslog',
            name='non_registered_persons',
        ),
        migrations.AddField(
            model_name='serverroomaccesslog',
            name='group_members',
            field=models.TextField(blank=True, help_text='Enter the full names of all group members, one per line.'),
        ),
    ]
