# Generated by Django 5.2.4 on 2025-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_serverroomaccesslog_additional_persons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverroomaccesslog',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='serverroomaccesslog',
            name='detailed_activities',
            field=models.JSONField(blank=True, help_text='A list of all checked activities.', null=True),
        ),
    ]
