# Generated by Django 5.2.4 on 2025-07-29 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_remove_serverroomaccesslog_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverroomaccesslog',
            name='scheduled_for_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
