# Generated by Django 5.2.4 on 2025-08-04 01:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_serverlocation_latitude_serverlocation_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverlocation',
            name='pic',
        ),
        migrations.AddField(
            model_name='serverlocation',
            name='pics',
            field=models.ManyToManyField(blank=True, related_name='pic_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
