# Generated by Django 5.2.4 on 2025-07-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serverlocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
